### PR TITLE
PMM-61 Create GitLens 12.2 release notes in Help Center

### PR DESCRIPTION
**Pull request by jjsilva4**
https://gitkraken.atlassian.net/browse/PMM-61

Hello support! Here is my initial draft of the GitLens 12.2 release notes.

To view it, you will need to build it through local and navigate to /gitlens/gitlens-release-notes-current/

Alex, can you help me update the navigation? I also need help updating any links on the Help Center home or left nav that push visitors to the GitHub changelog. It should go to this page instead

### CODE REVIEW

**Comment by Axxzilla** [comment]
`Alex, can you help me update the navigation? I also need help updating any links on the Help Center home or left nav that push visitors to the GitHub changelog.` 

Yep I can add the navigation in the left side once this is merged. What do we want added? It seems like we would just replace the current `Release Notes` that link out to instead be the page you created. 

Then on the H1 page we would want to change the `Release Notes` to point to the same page.

Is there anywhere else to update?

**Comment by jjsilva4** [comment]
> 

That's correct. I think we just need to update the links, and also remove the little icon arrow icon 
image

Also just noticed the GitLens+ features page will need to be updated with the new 12.2 features. Want me to roll that into this PR?

**Comment by jkelroy** [comment]
Just rebased my branch on top of Jonathans and then pushed to his remote. Looking into implementing your suggestions now.

**Comment by jkelroy** [comment]
@Axxzilla @jjsilva4 I dont see anything in the repository or Word Press about this - does anyone know where it comes from or how to change it?

> That's correct. I think we just need to update the links, and also remove the little icon arrow icon image

**Comment by Axxzilla** [comment]
@jkelroy and I went over how to do this is in wordpress ☝️

**Pull request merged**
